CREATE TABLE IF NOT EXISTS projects (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  git_url VARCHAR(1024),
  git_username VARCHAR(255),
  git_token VARCHAR(2048),
  auth_type VARCHAR(50) DEFAULT 'NONE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT NOT NULL,
  commit_id VARCHAR(255),
  status VARCHAR(50),
  result_summary TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES projects(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 如果已有 projects 表，请用 ALTER 添加列：
-- ALTER TABLE projects ADD COLUMN git_username VARCHAR(255), ADD COLUMN git_token VARCHAR(2048), ADD COLUMN auth_type VARCHAR(50) DEFAULT 'NONE';